version: 0.2
phases:
  install:
    runtime-versions:
        java: 8
  build:
    commands:
          - aws cloudformation package --template-file template.yaml --s3-bucket lamnewbucket --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml